### ISSUE TITLE
where can i get token and credentials?

### ISSUE THREAD

**Issue by amantiwari1** [ivangonzalezg/strapi-provider-email-googleapis#1]
credentialsPath: path.join(__dirname, "../credentials.json"),
      tokenPath: path.join(__dirname, "../token.json")

**Comment by ivangonzalezg** [comment]
Please follow these steps:

[https://developers.google.com/gmail/api/quickstart/nodejs](https://developers.google.com/gmail/api/quickstart/nodejs)
